### ISSUE TITLE
Support for TFS 2005

### ISSUE THREAD

**Issue by adamjenkin** [StanleyGoldman/TeamPilgrim#1]
I would really like to be able to use this extension against TFS 2005.

I am successfully using VS2012 against this version of TFS for everything else. When using the extension for pending changes, I can select the files I want to check-in, add a comment but when I hit the check-in button, nothing happens.

In the log file, there are lots of error messages with the following:

[Void OnDoWork(System.ComponentModel.DoWorkEventArgs)] => [Void PopulateBackgroundWorkerOnDoWork(System.Object, System.ComponentModel.DoWorkEventArgs)] => [Boolean TryGetBuildDefinitionsByProjectName(Microsoft.TeamFoundation.Build.Client.IBuildDefinition[] ByRef, Microsoft.TeamFoundation.Client.TfsTeamProjectCollection, System.String)]
2013-02-04 17:36:06.3266  12 TeamPilgrimServiceModelProvider DEBUG  
System.NotSupportedException: TF214015: The build client object model does not support Team Foundation Server 2005.
   at Microsoft.TeamFoundation.Build.Client.BuildServer.Microsoft.TeamFoundation.Client.ITfsTeamProjectCollectionObject.Initialize(TfsTeamProjectCollection tfs)
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection.InitializeTeamFoundationObject(String fullName, Object instance)
   at Microsoft.TeamFoundation.Client.TfsConnection.CreateServiceInstance(Assembly assembly, String fullName)
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection.GetServiceInstance(Type serviceType, Object serviceInstance)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService(Type serviceType)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService[T]()
   at JustAProgrammer.TeamPilgrim.VisualStudio.Business.Services.TeamPilgrimTfsService.QueryBuildDefinitions(TfsTeamProjectCollection tfsTeamProjectCollection, String teamProject)
   at JustAProgrammer.TeamPilgrim.VisualStudio.Providers.TeamPilgrimServiceModelProvider.TryGetBuildDefinitionsByProjectName(IBuildDefinition[]& buildDefinitions, TfsTeamProjectCollection collection, String projectName)

**Comment by StanleyGoldman** [comment]
Yea, I tried to solve that problem myself as well.

That error above is during initialization. There is another one in your  log regarding the commit operation.

I was hoping this [msdn question](http://social.msdn.microsoft.com/Forums/en-US/tfsversioncontrol/thread/09cc6ecb-500c-4a9e-ab3f-8cecfbaae8ff/#d32b2bc3-3884-469f-82a1-173703d68d19) would help me figure it out

The problem is that Visual Studio 2012 generally doesn't play with TFS2005.
I'm using references to Visual Studio 2012's Team Explorer, locally and in the GAC.

From what I've read you have to use Visual Studio 2008's TFS Libraries.

Then you have two choices...
- Make TeamPilgrim connect to both
  - TeamPilgrim would need a special "Connect to TFS 2005" Button where it no longer listens to Visual Studio's TeamFoundationHost, and uses its own TFS 2005 connection.
  - In order to maintain >TFS2005 functionality you'd have to reference TFS 2008 libraries entirely through reflection.
- Make TeamPilgrim a TFS2005 only utility
  - You'd have to hardwire the work I mentioned above, but you wouldn't have to use reflection
  - Doing it this way is a good start at least

**Comment by StanleyGoldman** [comment]
> I am successfully using VS2012 against this version of TFS for everything else.

I missed that part of what you said, I'm quite surprised actually, I had built a TFS2005 server myself in VMWare.
I don't remember having any luck getting VS2012 to play with it even without TeamPilgrim.

It's possible I just might've need the right libraries in my GAC.
I only have VS2010 & VS2012 installed. Do you have VS2008 installed?

**Comment by adamjenkin** [comment]
I am the same, only 2010 and 2012 installed but have been using 2012 for a few months with no issues.

**Comment by StanleyGoldman** [comment]
Thankfully,

I didn't delete the TFS 2005 Virtual Machine, it was such a pain to get it
running.
Let me try to use it again soon. I'll see what I can find.

-Stan
